version: '3'
services:
  client:
    image: "josua96/multi-client"
    # hostname is like the named ip for the container that will be running this image
    # docker will redirect to this container all those request whose their hostname is client
    hostname: "client"
  server:
    image: "josua96/multi-server"
    hostname: "api"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "josua96/multi-worker"
    hostname: "worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "josua96/multi-nginx"
    hostname: nginx
    ports:
      - "80:80"